### PR TITLE
Refixed the ordering of the interface guids.

### PR DESCRIPTION
**Pull request by mzomparelli**
This works, test it. The GUIDs should be ordered.

### CODE REVIEW

**Comment by mzomparelli** [comment]
btw, I don't think the _0000 and others is doing anything. The windows build number only comes back with the first half as an int. I will be removing those. Prior to 22621 should work as long as the build is <= 20000. If not then let's get the info and make it work.

**Comment by Slion** [comment]
I don't really want to merge that as it is as I would like to keep `app.config` readable by keeping `serializeAs` set to Xml.

**Comment by mzomparelli** [comment]
> 

Show me? I did not change that part. App.config is created upon every build

**Comment by mzomparelli** [comment]
> > 
> 
> Show me? I did not change that part. App.config is created upon every build

I only changed Settings.settings and that chnaged app.config when I built to test

**Comment by mzomparelli** [comment]
It still has that
image

**Comment by mzomparelli** [comment]
oh you want xml

**Comment by Slion** [comment]
> I only changed Settings.settings and that chnaged app.config when I built to test

That's why I'm changing the `app.config` directly which admittedly is a bit of a mess too.

**Comment by mzomparelli** [comment]
Well string is fine. It's readable for me and it's Settings.settings that is creating app.config. Never ever modify app.config manually. Always modify in Settings.settings

**Comment by mzomparelli** [comment]
> Well string is fine. It's readable for me and it's Settings.settings that is creating app.config. Never ever modify app.config manually. Always modify in Settings.settings

Why maintain the guids in two places when you only have to do it in one place

**Comment by mzomparelli** [comment]
> > I only changed Settings.settings and that chnaged app.config when I built to test
> 
> That's why I'm changing the `app.config` directly which admittedly is a bit of a mess too.

Why do you need it Serialize as xml?

**Comment by mzomparelli** [comment]
Everytime you build you will lose the serialize xml you put in the app.config. Give me a good reason that you are modifying app.config manually.

**Comment by mzomparelli** [comment]
You didn't need to add the minor version to the builds. That is overkill. 22000 would have handled prior to 22621 I'm pretty sure and if it won't then we need to find those chnages.

**Comment by mzomparelli** [comment]
I'm going to undo that minor build stuff

**Comment by mzomparelli** [comment]
Do you know what build number came right before 22621?

**Comment by mzomparelli** [comment]
See I'm sure it'll work without the minor versions
image

**Comment by mzomparelli** [comment]
We should just take the int of the Build double

**Comment by Slion** [comment]
> Everytime you build you will lose the serialize xml you put in the app.config. Give me a good reason that you are modifying app.config manually.

It keeps `app.config` readable so that we can easily read the diffs as those UIDs are so important to keeping the whole thing working.

**Comment by mzomparelli** [comment]
I propose doing this
image

**Comment by Slion** [comment]
> You didn't need to add the minor version to the builds. That is overkill. 22000 would have handled prior to 22621 I'm pretty sure and if it won't then we need to find those chnages.

Because the UIDs changed between  22621.2134 and 22621.2215

**Comment by mzomparelli** [comment]
You didn't even add the minor to the namespace
image

**Comment by mzomparelli** [comment]
We are getting rid of the minor and going back to only the major

**Comment by mzomparelli** [comment]
> 

2134 is not even a valid build. Was that insider? We don't support old insiders forever.

**Comment by Slion** [comment]
> > 
> 
> 2134 is not even a valid build. Was that insider? We don't support old insiders forever.

No it was the official build before 2215 came along a few days ago.

**Comment by mzomparelli** [comment]
> > > 
> > 
> > 
> > 2134 is not even a valid build. Was that insider? We don't support old insiders forever.
> 
> No it was the official build before 2215 came along a few days ago.

But 22000 works for that build right?

The >= logic would have caught it for 22000

image

**Comment by Slion** [comment]
> You didn't even add the minor to the namespace image

Oups, looks like it is not strictly needed. Feel free to fix it though.

**Comment by Slion** [comment]
> But 22000 works for that build right?

The provider yes. But not the UIDs.

**Comment by Slion** [comment]
So 22621.2134 was using the 22000 provider with UIDs specific to 22621. Then 2215 came along.
I too like to keep things simple but if Microsoft changes those UIDs between minor version then we need to take them into account too.

**Comment by mzomparelli** [comment]
> rovider yes. But not the UIDs.

2134 is identical to 22000

image

**Comment by Slion** [comment]
I've fixed the ordering on main while keeping `app.config` clean. Hope you don't mind.

**Comment by mzomparelli** [comment]
I do actually. We don't modify app.config. Tell me why you need app.config a certain way? Also I'm undoing the minor stuff you added as I just confirmed 22000 is the same as 22621.2134

**Comment by mzomparelli** [comment]
can you undo to my commit from last night

**Comment by mzomparelli** [comment]
I will fix the Settings.settings. guids after.

**Comment by Slion** [comment]
Apologize I probably got confused with the UID being different for 22000 and 22621 before 2215. But the fact remain that since the UIDs are changing between minor versions we need to take it into account.

**Comment by mzomparelli** [comment]
No the minor version don't matter. I just confirmed that 22621.2134 matches 22000. I've been maintaining my own for a while and I only use the major build

**Comment by mzomparelli** [comment]
You're killing me. I'm starting ,my own fork and I won't do pull requests

**Comment by Slion** [comment]
Fair enough and too bad… 😭
Hope for you they don't change those UIDs between minor versions again.
Trust me I did not implement that because I fancy doing it.

**Comment by mzomparelli** [comment]
> Fair enough and too bad… 😭 Hope for you they don't change those UIDs between minor versions again. Trust me I did not implement that because I fancy doing it.

Yes you did. It's unnecessary and creates more code than necessary. Also more to maintain.

**Comment by mzomparelli** [comment]
> hat because I fancy doing it.

You still didnt give me a valid reason for manually modifying app.config and why you need it serialize xml

**Comment by mzomparelli** [comment]
You would think you would trust the guy that fixed this for you

**Comment by Slion** [comment]
> Yes you did. It's unnecessary and creates more code than necessary. Also more to maintain.

Sad you won't trust me. That's the reason why #1 was created and why people started turning up asking for a fix.
The UIDs were changed between 22621.2134 and 22621.2215 which was released a few days ago.

**Comment by mzomparelli** [comment]
No they were not. Tell me this, was this library working for 22621.2134? If so then it was using 22000. I confirmed they are the same.

Please trust me and take my next pull

**Comment by Slion** [comment]
> You would think you would trust the guy that fixed this for you

Your are awesome man. I'm most impressed with your work on reverse engineering and I really wish we could find common ground and work together on that one.

**Comment by mzomparelli** [comment]
Then trust my changes. Actuially prove to me it does not work on 22621.2134. I know my changes will

**Comment by Slion** [comment]
> Tell me this, was this library working for 22621.2134?

Yes it was. That's actually the reason I started that fork.

**Comment by mzomparelli** [comment]
ok then there was no need to add minor build

**Comment by Slion** [comment]
I meant it was working on 2134 before your changes that fixed it for 2215.

**Comment by mzomparelli** [comment]
You're wrong. I will test it myself. I'm reverting your changes so I can test it and show you the proper way

**Comment by Slion** [comment]
I would gladly be proven wrong as it means the code would remain less complex albeit marginally.

**Comment by mzomparelli** [comment]
Also you should understand 22621.2134 not a full build. It's the same as 22000 for Virtual Desktops. 2134 is not a build that Microsoft will give you anymore. 22H2 is 2215, 22H1 is 22000

**Comment by Slion** [comment]
> Also you should understand 22621.2134 not a full build. It's the same as 22000 for Virtual Desktops. 2134 is not a build that Microsoft will give you anymore. 22H2 is 2215, 22H1 is 22000

I know but there is potentially still people out there who are still running 2134 until they upgrade to 2215 like I did a couple of days ago.

**Comment by mzomparelli** [comment]
ok but 2134 will use 22000. I will prove it just give me a bit. Do you have 2134 installed and ready?

**Comment by Slion** [comment]
> ok but 2134 will use 22000. I will prove it just give me a bit. Do you have 2134 installed and ready?

No that's the point I don't have a machine running it anymore.

**Comment by mzomparelli** [comment]
Well go get an iso for it and setup a VM. You are assuming stuff and creating code we don't need

**Comment by Slion** [comment]
Do you think I could just uninstall KB5029351 which is 22621.2215?

**Comment by mzomparelli** [comment]
possibly, but it's safer to just get the iso and setup a VM. I'll do it. Will you be able to attend a screenshare when I have it ready?

**Comment by Slion** [comment]
> You are assuming stuff and creating code we don't need

Not assuming 😁 I saw it before my own eyes. VirtualDesktop worked, do windows update reboot, VirtualDesktop don't work…

**Comment by mzomparelli** [comment]
Ok, I trust that something happened for you, but based on the code I'm certain it will work without the minor. I will set it up and prove it.

**Comment by Slion** [comment]
> possibly, but it's safer to just get the iso and setup a VM. I'll do it. Will you be able to attend a screenshare when I have it ready?

Depends when that would be. I'm GMT+1 don't have anything planned tonight though, other than getting a good night rest.

**Comment by mzomparelli** [comment]
It won't have to be today. Your code works and can stay for now, but I will prove this and we will do away with minor version. When I prove it you will take my commit that does away with minor, right?

**Comment by Slion** [comment]
Of course if we can prove there is not need for the minor version check I would gladly do without it.

**Comment by Slion** [comment]
As for the `app.config` and settings issue there must be a way to use the settings wizard so that it generates a cleaner config.
Here is what it looks like on my machine:
image

**Comment by mzomparelli** [comment]
but why is the app.config so important to you? It looks fine to me and users should not change it. It's created when we build and the only reason for a change to it is when we build. There is no reason to modify app.config after compile.

**Comment by Slion** [comment]
To me, easy to read diffs is important to keep track of those changes. If every contributor comes along with a different version of Visual Studio and keep pushing unneeded changes just because on that day with that version of Visual Studio the code generator decided to do something different we keep on polluting the file history which would make it hard to track regressions down the road. Hope that makes sense.

**Comment by mzomparelli** [comment]
We don't modify app.config. It's created from Settings.setitngs at compile time

**Comment by mzomparelli** [comment]
https://files.rg-adguard.net/version/f0bd8307-d897-ef77-dbd6-216fefbe94c5

I have undone your changes and have it working on 22621.2215. I am now getting the iso for 2134

**Comment by Slion** [comment]
> https://files.rg-adguard.net/version/f0bd8307-d897-ef77-dbd6-216fefbe94c5

Thanks for that link, that could be useful.

**Comment by mzomparelli** [comment]
well getting that specific version is not easy, but I will keep trying

**Comment by mzomparelli** [comment]
well if it's not easy then why are we supporting it?

**Comment by mzomparelli** [comment]
even though I'm sure my code will in fact support it

**Comment by Slion** [comment]
> well if it's not easy then why are we supporting it?

For smooth transitions while users are upgrading. You could try any 22621 build before 2215 and it should not work with the new UIDs.

**Comment by mzomparelli** [comment]
ok' I'll try one that is earlier than 2215 if I can find.

**Comment by mzomparelli** [comment]
if you find a link then post it. I have some downloading that I hink will work. I have a feeling that Microsoft will perform the update during installation though

**Comment by Slion** [comment]
You could install offline.

**Comment by mzomparelli** [comment]
> You could install offline.

Are you sure? I'll try but I though MS makes you be connected.

**Comment by mzomparelli** [comment]
Please no more commits until I am done. I will be done today. I just don't our repos to be out of sync.

**Comment by mzomparelli** [comment]
I have this - I think it'll do. Installing now
en-us_windows_11_consumer_editions_version_22h2_updated_sep_2022_x64_dvd_f408dad5

**Comment by mzomparelli** [comment]
Do you know how to get around this?
image

**Comment by mzomparelli** [comment]
I think I got it

**Comment by Slion** [comment]
I'm booting up a laptop that could have a version we could use for testing.

**Comment by Slion** [comment]
Nevermind that's Windows 10 laptop…

**Comment by mzomparelli** [comment]
I have 22621.525 and I'm testing it now

**Comment by Slion** [comment]
Let me guess, it's not working the way you thought it would? 😁
You know using both OS Build major and minor version really is not much more complex than just checking the major version.
Also the current implementation is rather clumsy. I don't think we should assume major is 5 digits and minor is 4 digits. So there is a lot to improve on there. However checking the whole OS Build makes this solution future proof and I think that's what we should be aiming for.

**Comment by mzomparelli** [comment]
ok ok you win, but you don't need the Settings.settings for 22621_0000 because it's the same as 22000 and it falls back fine. I just tested.

**Comment by mzomparelli** [comment]
So I am keeping your changes, but I am removing 22621_0000 and I am also adding support for Server 2019 and 2022

**Comment by mzomparelli** [comment]
I would like to point out that we should not even support 22621 < 2215 as Microsoft will quickly update you past that now. Shame on them for keeping the major build number while having interface changes.

**Comment by Slion** [comment]
> ok ok you win, but you don't need the Settings.settings for 22621_0000 because it's the same as 22000 and it falls back fine. I just tested.

That is correct. I believe 22621_0000 is just a left over of my implementation process. It does no harm but is also not needed and can thus be discarded. Also it's not about winning or loosing it is about getting it right.

**Comment by mzomparelli** [comment]
My first commit is just removing that 22621_0000. the next commit after that will be for support for server 2019 and 2022

**Comment by mzomparelli** [comment]
Win server 2022 is build 20348, so we will need the 22621_0000 back in in order to support server. Ugh!

**Comment by mzomparelli** [comment]
oh nevermind, I got confused. We don't need it back in

**Comment by Slion** [comment]
> I would like to point out that we should not even support 22621 < 2215 as Microsoft will quickly update you past that now. Shame on them for keeping the major build number while having interface changes.

If I had to take a guess I think there is a lot more < 2215 than >= 2215 today and for weeks or maybe even months to come. The amazing flexibility this library offers thanks to @Grabacr07 and other contributors allows us to support all those versions and I am of the opinion we should try to keep it that way. Though I have to admit we could greatly reduce the complexity and just decide to support the latest and greatest at some point. Let's hope it does have to come to that.

And yes it did look like until recently only major updates would come with interface changes. Though I can't say I'm surprised they did that.

**Pull request closed without merging**
